set(__QT_DEPLOY_TARGET_CGAL_Qt6_moc_and_resources_FILE /home/voidbatnew/eth/year2/sem1/project/cgshop2026/src/libCGAL_Qt6_moc_and_resources.a)
set(__QT_DEPLOY_TARGET_CGAL_Qt6_moc_and_resources_TYPE STATIC_LIBRARY)
set(__QT_DEPLOY_TARGET_centralTriangulation_FILE /home/voidbatnew/eth/year2/sem1/project/cgshop2026/src/centralTriangulation)
set(__QT_DEPLOY_TARGET_centralTriangulation_TYPE EXECUTABLE)
